### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by sysu18364023** [ZJU-FAST-Lab/std-trees#1]
您好，我在编译的过程中遇到如下报错：

[100%] Linking CXX executable /home/fanjf/catkin_ws/devel/lib/state_machine/test_planner_node
/usr/bin/ld: warning: libgfortran.so.3, needed by /home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so, not found (try using -rpath or -rpath-link)
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_transfer_real_write@GFORTRAN_1.4’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_st_write_done@GFORTRAN_1.0’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_transfer_integer_write@GFORTRAN_1.4’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_etime@GFORTRAN_1.0’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_stop_numeric_f08@GFORTRAN_1.4’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_st_write@GFORTRAN_1.0’未定义的引用
collect2: error: ld returned 1 exit status
std-trees/decision/state_machine/CMakeFiles/test_bvp_node.dir/build.make:419: recipe for target '/home/fanjf/catkin_ws/devel/lib/state_machine/test_bvp_node' failed
make[2]: *** [/home/fanjf/catkin_ws/devel/lib/state_machine/test_bvp_node] Error 1
CMakeFiles/Makefile2:9643: recipe for target 'std-trees/decision/state_machine/CMakeFiles/test_bvp_node.dir/all' failed
make[1]: *** [std-trees/decision/state_machine/CMakeFiles/test_bvp_node.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
/usr/bin/ld: warning: libgfortran.so.3, needed by /home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so, not found (try using -rpath or -rpath-link)
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_transfer_real_write@GFORTRAN_1.4’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_st_write_done@GFORTRAN_1.0’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_transfer_integer_write@GFORTRAN_1.4’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_etime@GFORTRAN_1.0’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_stop_numeric_f08@GFORTRAN_1.4’未定义的引用
/home/fanjf/catkin_ws/src/std-trees/planning/poly_opt/lib/lmbm.so：对‘_gfortran_st_write@GFORTRAN_1.0’未定义的引用
collect2: error: ld returned 1 exit status
std-trees/decision/state_machine/CMakeFiles/test_planner_node.dir/build.make:419: recipe for target '/home/fanjf/catkin_ws/devel/lib/state_machine/test_planner_node' failed
make[2]: *** [/home/fanjf/catkin_ws/devel/lib/state_machine/test_planner_node] Error 1
CMakeFiles/Makefile2:9737: recipe for target 'std-trees/decision/state_machine/CMakeFiles/test_planner_node.dir/all' failed
make[1]: *** [std-trees/decision/state_machine/CMakeFiles/test_planner_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

想咨询一下您，是哪方面的报错，应该如何处理呢？

**Comment by kyleYehh** [comment]
缺少了libgfortran.so.3这个库文件，
你先运行这个命令安装：sudo apt install libgfortran3
之后再编译。抱歉这么久才看到
